create database quanlysinhvien;
GO

use quanlysinhvien;
GO

CREATE TABLE SINHVIEN (
	MASV CHAR(6) NOT NULL,
	HOSV NVARCHAR(30) NOT NULL,
	TENSV NVARCHAR(30) NOT NULL,
	GIOITINH CHAR(3) NULL,
	NGAYSINH DATE NULL,
	NOISINH NVARCHAR(50) NULL,
	DIACHI NVARCHAR(50) NULL,
	QUAN NVARCHAR(6) NULL,
	MAKHOA CHAR(6) NULL,
	HOCBONG INT NULL,
	PRIMARY KEY(MASV)
);
GO

CREATE TABLE KETQUA(
 MASV CHAR(6) NOT NULL,
 MAMH CHAR(6) NOT NULL,
 DIEMTHI INT NULL,
 PRIMARY KEY(MASV,MAMH)
);
GO

CREATE TABLE MONHOC(
MAMH CHAR(6) NOT NULL,
TENMH NVARCHAR(50) NOT NULL,
SOTIET INT NULL
PRIMARY KEY(MAMH)
);
GO

CREATE TABLE KHOA(
MAKHOA CHAR(6) NOT NULL,
TENKHOA NVARCHAR(30) NULL
PRIMARY KEY(MAKHOA)
);
GO

ALTER TABLE SINHVIEN 
ADD FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA) ;
GO

ALTER TABLE KETQUA
ADD FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);
GO

ALTER TABLE KETQUA
ADD FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);
GO

SELECT * FROM SINHVIEN
GO

INSERT INTO KHOA(MAKHOA,TENKHOA)
VALUES('KH01',N'KHOA CÔNG NGHỆ THÔNG TIN')
GO

INSERT INTO SINHVIEN(MASV,HOSV,TENSV,GIOITINH,NGAYSINH,NOISINH,DIACHI,QUAN,MAKHOA,HOCBONG)
VALUES('SV01',N'TRAN','VAN A','NAM','1/1/2000','HO CHI MINH CITY','11A dung tran hung dao',N'quan 1','KH01',0)
GO

 DELETE SINHVIEN WHERE MASV = 'SV01'
 GO

 UPDATE SINHVIEN SET MASV = 'SV02' WHERE MASV = 'SV01'
 GO

 CREATE Proc insertSinhVien (
	@MASV CHAR(6) ,
	@HOSV NVARCHAR(30) ,
	@TENSV NVARCHAR(30) ,
	@GIOITINH CHAR(3) ,
	@NGAYSINH DATE ,
	@NOISINH NVARCHAR(50) ,
	@DIACHI NVARCHAR(50) ,
	@QUAN NVARCHAR(6) ,
	@MAKHOA CHAR(6) ,
	@HOCBONG INT 
)
AS 
INSERT INTO SINHVIEN(MASV,HOSV,TENSV,GIOITINH,NGAYSINH,NOISINH,DIACHI,QUAN,MAKHOA,HOCBONG)
VALUES (@MASV,@HOSV,@TENSV,@GIOITINH,@NGAYSINH,@NOISINH,@DIACHI,@QUAN,@MAKHOA,@HOCBONG)
GO

CREATE PROC deleteSinhVien(
	@MASV CHAR(6)
)
AS 
DELETE SINHVIEN WHERE MASV = @MASV
GO

CREATE PROC selectSinhVien
AS 
SELECT * FROM SINHVIEN
GO

CREATE PROC updateSinhVien(
	@MASV CHAR(6) ,
	@HOSV NVARCHAR(30) ,
	@TENSV NVARCHAR(30) 
)
AS
UPDATE SINHVIEN
SET  HOSV = @HOSV, TENSV = @TENSV
WHERE MASV = @MASV
GO





Exec insertSinhVien 'SV03',N'TRAN','VAN A','NAM','1/1/2000','HO CHI MINH CITY','11A dung tran hung dao',N'quan 1','KH01',0;
Exec deleteSinhVien 'SV02';
Exec selectSinhVien ;
EXEC updateSinhVien 'SV01',N'TRẦN',N'VĂN A';
GO


CREATE PROC themKhoaSP (
	@MAKHOA CHAR(6) ,
	@TENKHOA NVARCHAR(30) 
)
AS
INSERT INTO  KHOA(MAKHOA,TENKHOA) 
VALUES (@MAKHOA,@TENKHOA)
GO

CREATE PROC sp_LayDanhSachKhoa
AS
SELECT * FROM KHOA
GO

CREATE PROC sp_LayDanhSachMonHoc
AS
SELECT * FROM MONHOC
GO

CREATE PROC sp_ThemMonHoc(
	@MAMH CHAR(6) ,
	@TENMH NVARCHAR(50),
	@SOTIET INT 
)
AS
INSERT INTO MONHOC(MAMH,TENMH,SOTIET)
VALUES(@MAMH,@TENMH,@SOTIET)
GO

CREATE PROC sp_LayDSMaKhoa
AS
SELECT MAKHOA FROM KHOA

DELETE MONHOC WHERE MAMH = 'lap tr';

EXEC sp_LayDSMaKhoa

CREATE PROC TIMTENMONHOC(
	@TENMH NVARCHAR(50)
)
AS 
SELECT * 
FROM MONHOC 
WHERE TENMH LIKE '%'+@TENMH+'%'
GO

SELECT * FROM MONHOC
EXEC TIMTENMONHOC 'LTUD'


CREATE PROC sp_SapXep
AS
SELECT * 
FROM MONHOC
ORDER BY MAMH DESC

/* ASC */
/*DROP PROC TIMTENMONHOC */

EXEC sp_SapXep